### ISSUE TITLE
permission?

### ISSUE THREAD

**Issue by balinbob** [madmaxms/iconpack-delft#12]
Marcus, I used your media-player icons from this theme in an open-source project.   It is called yrc.   It is on Github under my username.   I don't want to spam you with the link.

You have some excellent icons!  Thank you.

I hope you will give me your permission if that is necessary.

balinbob
Bob Allred
USA

**Comment by madmaxms** [comment]
Hey Bob, it is not necessary, but anyway, you have my permission :-)
