### ISSUE TITLE
Join efforts with faience-next-generation

### ISSUE THREAD

**Issue by FabioLolix** [madmaxms/iconpack-delft#3]
Would you like to join @o1ux at https://github.com/faience to make only one continuated Faience icon theme?

**Comment by madmaxms** [comment]
Sure I would! :-)
At the moment it looks like it is not bigger than any other Faenza fork out there (which I could join as well). But I'll keep watching it, and if it becomes bigger and more known, I'd be glad to join it completely and having more time for my other projects ;-)
The guy behind it may gladly take everything he needs from this project.
