### ISSUE TITLE
Fix: Transmission Remote icon

### ISSUE THREAD

**Issue by jooola** [madmaxms/iconpack-delft#7]
It would be nice to use the Transmission icon for the Transmission Remote app, but with a small modification, maybe something that mean remote ?

Currently the icon isn't supported : 
![image](https://user-images.githubusercontent.com/19195485/49285609-32d7a600-f498-11e8-86e4-cb23651ae131.png)

**Comment by madmaxms** [comment]
Fixed

**Comment by jooola** [comment]
Thanks a lot ! Great work !
